# Generated by Django 3.0.6 on 2020-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Neha Awesome blog !!!!!!!', max_length=255),
        ),
    ]
